{
 "title": "Ignite nodes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CpuLoad",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sys_CpuLoad", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "mid-proxy session statistics",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mid_proxy_session_start_total", "legendFormat": "START:{{instance}}" },
    { "expr": "mid_proxy_session_poll_total", "legendFormat": "POLL:{{instance}}" },
    { "expr": "mid_proxy_session_result_total", "legendFormat": "RESULT:{{instance}}" },
    {
     "expr": "mid_proxy_session_result_requested_total",
     "legendFormat": "RESULT requested: {{instance}}"
    },
    {
     "expr": "mid_proxy_session_exception_total",
     "legendFormat": "EXCEPTION:{{instance}}"
    },
    { "expr": "mid_proxy_session_retry_total", "legendFormat": "RETRY:{{instance}}" }
   ]
  },
  {
   "title": "GcCpuLoad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sys_GcCpuLoad", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "cache.MID_REQUEST_CacheSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "cache_MID_REQUEST_CacheSize{job=\"ignite\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ThreadCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "sys_ThreadCount", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MID_REQUEST cache Put/Remove/Evict",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "cache_MID_REQUEST_CacheEvictions{job=\"ignite\"}",
     "legendFormat": "Evict:{{instance}}"
    },
    {
     "expr": "cache_MID_REQUEST_CacheRemovals{job=\"ignite\"}",
     "legendFormat": "Remove: {{instance}}"
    },
    {
     "expr": "cache_MID_REQUEST_CachePuts{job=\"ignite\"}",
     "legendFormat": "Put:{{instance}}"
    }
   ]
  },
  {
   "title": "cluster.ActiveBaselineNodes",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "cluster_ActiveBaselineNodes", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "cluster.Rebalanced",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "cluster_Rebalanced{job=\"ignite\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}