global:
  scrape_interval:     1s
  evaluation_interval: 1s
  
scrape_configs:
  - job_name: "mid-proxy"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["mid-rest-proxy-01.localhost:8081", "mid-rest-proxy-02.localhost:8082", "mid-rest.localhost:8083"]
  - job_name: "ignite"
    static_configs:
      - targets: ["ignite-01.localhost:7070", "ignite-02.localhost:7070"]